version: '3.9'

services:
  backend:
    build:
      context: .app/
      dockerfile: Dockerfile.backend
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery:
    build:
      context: .app/
      dockerfile: Dockerfile.celery
    container_name: celery_worker
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - backend
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"    
    volumes:
          - redis_data:/data


  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.frontend
    container_name: vite_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  nginx:
    build:
      context: ./front
      dockerfile: Dockerfile.nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend


volumes:
  postgres_data:
  redis_data:
