version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: ./app/Dockerfile.backend
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file:
      - .env
    depends_on:
      - db
      - redis
    networks:
      - backend
    expose:
      - "8000"

  celery:
    build:
      context: .
      dockerfile: ./app/Dockerfile.celery
    container_name: celery_worker
    env_file:
      - .env
    depends_on:
      - backend
      - redis
    networks:
      - backend


  redis:
    image: redis:7
    container_name: redis
    volumes:
      - redis_data:/data
    networks:
      - backend

  db:
    image: postgres:17
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile.frontend
    container_name: vite_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - frontend
      - backend

volumes:
  postgres_data:
  redis_data:

networks:
  frontend:
  backend:
