# Étape 1 : build avec Node
FROM node:20.19 AS builder
WORKDIR /app
COPY . .
RUN npm install
RUN npm run build

# Étape 2 : serveur statique avec Nginx
FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
